local prettier = require('prettier')

prettier.setup {
    bin = 'prettier',
    filetypes = {
        'javascript',
        'javascriptreact',
        'javascript.jsx',
        'typescript',
        'typescriptreact',
        'typescript.tsx',
        'json',
        'jsonc',
        'css',
        'scss',
        'less',
        'graphql',
        'markdown',
        'vue',
        'yaml',
        'html',
        'twig',
        'php',
        'python',
        'ruby',
        'lua',
        'java',
        'kotlin',
        'scala',
        'swift',
        'c',
        'cpp',
        'rust',
        'go',
        'dart',
        'shell',
        'powershell',
        'dockerfile',
        'plaintext',
    },
}