local ts = require('nvim-treesitter.configs')

ts.setup {
    highlight = {
      enable = true,
      disable = {},
    },
    indent = {
      enable = true,
      disable = {},
  },
  ensure_installed = {
      "javascript",
      "typescript",
      "tsx",
      "json",
      "html",
      "css",
      "scss",
      "lua",
      "python",
      "rust",
      "go",
      "yaml",
      "toml",
      "json",
      "graphql",
      "bash",
      "dockerfile",
      "c",
      "cpp",
      "java",
      "php",
      "ruby",
      "swift",
      "regex",
      "vue",
      "svelte",
      "tsx",
      "rust",
      "html",
      "css",
      "scss",
      "lua",
      "python",
      "rust",
      "go",
      "yaml",
      "toml",
      "json",
      "graphql",
      "bash",
      "dockerfile",
      "c",
      "cpp",
      "java",
      "php",
      "ruby",
      "swift",
      "regex",
      "vue",
      "svelte",
      "tsx",
  },
  autotag = {
      enable = true,
  },
}